## 本地图片上传路径，但是在本项目没有使用上传功能，上传使用的是原项目的服务器
local:
  path: /Users/le/Documents/image/mall
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: newbee_mall_db_v2
  username: root
  password: root
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
